// <auto-generated />
using EmployeeSamGTU;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeSamGTU.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeSamGTU.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Angular")
                        .HasColumnType("integer");

                    b.Property<int>("AspNet")
                        .HasColumnType("integer");

                    b.Property<int>("BasicCsharp")
                        .HasColumnType("integer");

                    b.Property<int>("BasicJS")
                        .HasColumnType("integer");

                    b.Property<int>("BasicJava")
                        .HasColumnType("integer");

                    b.Property<int>("BasicPython")
                        .HasColumnType("integer");

                    b.Property<int>("Bootstrap")
                        .HasColumnType("integer");

                    b.Property<int>("Django")
                        .HasColumnType("integer");

                    b.Property<int>("Entity")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Flask")
                        .HasColumnType("integer");

                    b.Property<int>("GuiJava")
                        .HasColumnType("integer");

                    b.Property<int>("HtmlAndCss")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReactJS")
                        .HasColumnType("integer");

                    b.Property<double>("Salary")
                        .HasColumnType("double precision");

                    b.Property<int>("Sass")
                        .HasColumnType("integer");

                    b.Property<int>("SpringJava")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
